stages:
  data_ingestion:
    cmd: python src/breastCancer/pipeline/stage_01_data_ingestion.py
    deps:
      - src/breastCancer/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      - data/data.csv
    outs:
      - artifacts/data_ingestion/data.csv

  data_validation:
    cmd: python src/breastCancer/pipeline/stage_02_data_validation.py
    deps:
      - src/breastCancer/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/data.csv
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/breastCancer/pipeline/stage_03_data_transformation.py
    deps:
      - src/breastCancer/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/data.csv
    outs:
      - artifacts/data_transformation/data_clean.csv

  training:
    cmd: python src/breastCancer/pipeline/stage_04_model_trainer.py
    deps:
      - src/breastCancer/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_transformation/data_clean.csv
    params:
      - LogisticRegression.penalty
      - LogisticRegression.tol
    outs:
      - artifacts/model_trainer

  evaluation:
    cmd: python src/breastCancer/pipeline/stage_05_model_evaluation.py
    deps:
      - src/breastCancer/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data_transformation/data_clean.csv
      - artifacts/model_trainer/model.pkl
      - artifacts/model_trainer/scaler.pkl
    params:
      - LogisticRegression.penalty
      - LogisticRegression.tol
    metrics:
      - artifacts/model_evaluation/metrics.json:
          cache: false
