artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data: data/data.csv
  local_data_file: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  data_clean_path: artifacts/data_transformation/data_clean.csv

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/data_clean.csv
  model_path: artifacts/model_trainer/model.pkl
  scaler_path: artifacts/model_trainer/scaler.pkl
